### ISSUE TITLE
Feature Idea: Scan Quality Score

### ISSUE THREAD

**Issue by nickpending** [antfie/scan_health#12]
Is it possible to include the scan quality score in the output? I know there's an internal report that includes that metric and it would be very useful to have in this tool.

**Comment by antfie** [comment]
The SAST scan quality score is at present only available to Veracode staff. There is unfortunately no API for this information so this tool cannot surface that. You may want to suggest Veracode provides this information via an API by raising a new idea over at https://community.veracode.com/s/ideas. I would not like to attempt to compute a health score using the data from this tool as that could get confusing and would not match the calcualtion we use internaly, which relies on other data not available via the APIs.
