### ISSUE TITLE
Bug: if the cache for a scan includes an error, it corrupts future calls to that scan

### ISSUE THREAD

**Issue by dipsylala** [antfie/scan_health#13]
Additional apps or the user may call scan_health with the `-cache=true` parameter. 

If the call to the SAST scan returns an error in the detailed XML, that error gets recorded in the cache. The error may be due to invalid API credentials.

Suggestion - only cache the detailed XML response if it is successful.

**Comment by antfie** [comment]
This has been addressed in https://github.com/antfie/scan_health/commit/0431027c1c5475f5207039f91618f7fd4fab1861.
