### ISSUE TITLE
Feature idea: check for consistency across scans

### ISSUE THREAD

**Issue by relaxnow** [antfie/scan_health#2]
Make sure you're always scanning (roughly) the same thing, some customers will scan wildly different things in different scans leading to flaw matching issues.

**Comment by antfie** [comment]
This is on the roadmap. Thanks for this suggestion.

**Comment by dipsylala** [comment]
I've started this as part of a separate branch. Given some scans can be huge, I've included the ability to omit the check if necessary. We're at the stage where the previous scan's data is available to the plugin and we need to decide on the kinds of checks to make (module selection differences, file upload differences, module differences). https://github.com/antfie/scan_compare for more ideas? :D

**Comment by antfie** [comment]
The previous scan check feature developed by @dipsylala has now been merged into https://github.com/antfie/scan_health/tree/main. Release [2.32](https://github.com/antfie/scan_health/releases/tag/2.32) contains this feature which can be enabled by passing `-previous-scan=true`
